@CardgameServer_HostAddress = http://localhost:5059

GET {{CardgameServer_HostAddress}}/player/3144302627708604081
Accept: application/json

###

POST {{CardgameServer_HostAddress}}/player
Content-Type: application/json

{ "Name": "P1" }

###

POST {{CardgameServer_HostAddress}}/player
Content-Type: application/json

{ "Name": "P2" }

###

POST {{CardgameServer_HostAddress}}/player
Content-Type: application/json

{ "Name": "P3" }

###

POST {{CardgameServer_HostAddress}}/player
Content-Type: application/json

{ "Name": "P4" }

###

GET {{CardgameServer_HostAddress}}/player?email=P1
Accept: application/json

###

POST {{CardgameServer_HostAddress}}/game/truco

###

GET {{CardgameServer_HostAddress}}/game/truco/107601453

###

GET {{CardgameServer_HostAddress}}/game/truco/107601453?playerid=1075994271

###

POST {{CardgameServer_HostAddress}}/game/truco/1921673180767473586/join?playerid=2737168940898381046

###

POST {{CardgameServer_HostAddress}}/game/truco/8390378804929350160/join?playerid=8523345388467627921

###

POST {{CardgameServer_HostAddress}}/game/truco/8390378804929350160/join?playerid=4405084404353215626

###

GET {{CardgameServer_HostAddress}}/game/truco/0

###

POST {{CardgameServer_HostAddress}}/game/truco

###

POST {{CardgameServer_HostAddress}}/game/truco

###

GET {{CardgameServer_HostAddress}}/game/truco/418080371/notifications?playerid=1220497722&timeout=60&startAt=0

###

POST {{CardgameServer_HostAddress}}/game/truco/join
Content-Type: application/json

"4444"

###

GET {{CardgameServer_HostAddress}}/game/truco/418080371/notification?playerid=288314161&startat=0&timeout=10

###

GET {{CardgameServer_HostAddress}}/game/truco/1698182366?playerid=288314161
###

GET {{CardgameServer_HostAddress}}/game/truco/1698182366/notifications?playerid=288314161&timeout=60&startAt=0

###